### ISSUE TITLE
1D dihedral scan fails with psi4 / python8

### ISSUE THREAD

**Issue by dvolkmer** [lpwgroup/torsiondrive#62]
Hello,

I am facing program stability issues for torsiondrive in 1D scans utilzing psi4 as qce.
The error output is:
 Traceback (most recent call last):
  File "/home/dirk/miniconda3/bin/torsiondrive-launch", line 10, in <module>
    sys.exit(main())
  File "/home/dirk/miniconda3/lib/python3.8/site-packages/torsiondrive/launch.py", line 183, in main
    scanner.master()
  File "/home/dirk/miniconda3/lib/python3.8/site-packages/torsiondrive/dihedral_scanner.py", line 365, in master
    self.launch_opt_jobs()
  File "/home/dirk/miniconda3/lib/python3.8/site-packages/torsiondrive/dihedral_scanner.py", line 593, in launch_opt_jobs
    job_path = self.launch_constrained_opt(m, to_grid_id)
  File "/home/dirk/miniconda3/lib/python3.8/site-packages/torsiondrive/dihedral_scanner.py", line 612, in launch_constrained_opt
    self.engine.launch_optimize(new_job_path)
  File "/home/dirk/miniconda3/lib/python3.8/site-packages/torsiondrive/qm_engine.py", line 79, in launch_optimize
    self.optimize_geomeTRIC()
  File "/home/dirk/miniconda3/lib/python3.8/site-packages/torsiondrive/qm_engine.py", line 301, in optimize_geomeTRIC
    self.run(cmd, input_files=['input.dat', 'constraints.txt'], output_files=['tdrive.log', 'tdrive.xyz', 'qdata.txt'])
  File "/home/dirk/miniconda3/lib/python3.8/site-packages/torsiondrive/qm_engine.py", line 104, in run
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/dirk/miniconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'geometric-optimize --prefix tdrive --qccnv --reset --epsilon 0.0 --enforce 0.1 --qdata --psi4 input.dat constraints.txt' returned non-zero exit status 51.

a test run of the HOOH example provided in the test directory finished normally.

Would be grateful if you could have a look at the appended input files and let me know what I might be doing wrong.

The input line I used was:
torsiondrive-launch -g 30 -e psi4 -c constraints.txt -v 1_rotor_short.dat dihedrals.txt
Thank you very much in advance !

Sincerely, Dirk

[constraints.txt](https://github.com/lpwgroup/torsiondrive/files/7513702/constraints.txt)
[dihedrals.txt](https://github.com/lpwgroup/torsiondrive/files/7513703/dihedrals.txt)

[1_rotor_short.dat.txt](https://github.com/lpwgroup/torsiondrive/files/7513710/1_rotor_short.dat.txt)

**Comment by xiki-tempula** [comment]
I'm getting the same error. This is due to the torsiondrive using geomeTRIC for geometry optimisation.
If you enable the --native_opt, it will work.

**Comment by dvolkmer** [comment]
Thank you very much for the advise. However, I am still facing problems:
Enabling the --native_opt geometry optimisation leads to the error message:
"extra constraints not supported in Psi4 native optimizations"

Sincerely, Dirk
