### ISSUE TITLE
Help with Error 

### ISSUE THREAD

**Issue by ss2780** [lpwgroup/torsiondrive#75]
Running the same file locally works fine, but remotely produces this error:

subprocess.CalledProcessError:`` Command 'geometric-optimize --prefix tdrive --qccnv --reset --epsilon 0.0 --enforce 0.1 --qdata --psi4 input.dat constraints.txt' returned non-zero exit status 1.

I can't work out why this this error only comes up sometimes, nor how to fix it.

**Comment by mattiafelice-palermo** [comment]
I am also facing the same error... Any insight?

I tried also to use the --native_opt option but I get:
```
Launching new job at opt_tmp/gid_-120/5
Traceback (most recent call last):
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/bin/torsiondrive-launch", line 10, in <module>
    sys.exit(main())
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/site-packages/torsiondrive/launch.py", line 183, in main
    scanner.master()
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/site-packages/torsiondrive/dihedral_scanner.py", line 365, in master
    self.launch_opt_jobs()
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/site-packages/torsiondrive/dihedral_scanner.py", line 593, in launch_opt_jobs
    job_path = self.launch_constrained_opt(m, to_grid_id)
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/site-packages/torsiondrive/dihedral_scanner.py", line 612, in launch_constrained_opt
    self.engine.launch_optimize(new_job_path)
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/site-packages/torsiondrive/qm_engine.py", line 77, in launch_optimize
    self.optimize_native()
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/site-packages/torsiondrive/qm_engine.py", line 286, in optimize_native
    self.run('psi4 input.dat -o output.dat', input_files=['input.dat'], output_files=['output.dat'])
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/site-packages/torsiondrive/qm_engine.py", line 104, in run
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/mpalermo/anaconda3/envs/torsion-psi4/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'psi4 input.dat -o output.dat' returned non-zero exit status 1.
```
When trying to run the command `psi4 input.dat -o output.dat`, the process work as expected and concludes gracefully.

Thank you for your help and if more information are needed, let me know :)

**Comment by mattiafelice-palermo** [comment]
For anyone reading, there are several issues of compatibility of torsiondrive with the new versions of psi4 and geometric. By modifying the source code accordingly, the software will run, but it took quite a bit of meddling to find out how. In the next days I'll try to report here the required modifications, since it seems pull requests are not being considered!

**Comment by jacob-votava** [comment]
Did you ever resolve this? @mattiafelice-palermo What modifications did you end up making?

**Comment by mattiafelice-palermo** [comment]
> Did you ever resolve this? [@mattiafelice-palermo](https://github.com/mattiafelice-palermo) What modifications did you end up making?

Hello! I forked the repo and made some modifications, including the fix mentioned above:
https://github.com/mattiafelice-palermo/torsiondrive-on-steroids

It also supports ORCA as engine, which is much more effective :)
